controledeartigos/articles/urls.py
from django.urls import path
from articles import views


app_name='articles'

urlpatterns = [
    path('flow/', views.flow_list_articles, name='flow_list_articles'),
    path('start/', views.start_list_articles, name='start_list_articles'),
    path('celero/', views.celero_list_articles, name='celero_list_articles'),
    path('novo_artigo/', views.create_article, name='create_article'),
    path('editar/<str:id>', views.edit_article, name='edit_article'),
    path('deletar/<str:id>', views.delete_article, name='delete_article'),
    path('deletados/', views.list_deleted_articles, name='list_deleted_articles'),
    path('recuperar/<str:id>', views.recuperate_article, name='recuperate_article'),
    path('realizado/<str:article_id>', views.change_article_to_done, name='change_to_done'),
    path('', views.get_user_pendent_articles, name='home'),
]

controledeartigos/controledeartigos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('artigos/', include('articles.urls', namespace='artigos')),
    path('accounts/', include("allauth.urls")),
    path('', include('articles.urls', namespace='home')),
]

controledeartigos/articles/models.py
from django.db import models
from django.db.models.base import Model
from django.contrib.auth.models import User
from django.db.models.fields import CharField
import uuid


class Article(models.Model):
    STATUS_CHOICES = (
        ('AF', 'A fazer'),
        ('FF', 'Feito'),
        ('AR', 'Atualizar'),
        ('AO', 'Atualizado')
    )

    PRODUCT_CHOICES = (
        ('CE', 'Celero'),
        ('ST', 'Start'),
        ('FW', 'Flow')
    )

    article_id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    name = models.CharField(max_length=150)
    url = models.URLField(max_length=200, null=True, blank=True)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES)
    last_updated = models.DateField(auto_now=True)
    owner = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    category = models.CharField(max_length=150, null=True, blank=True)
    product = models.CharField(max_length=2, choices=PRODUCT_CHOICES)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name

controledeartigos/articles/forms.py
from django import forms

from articles.models import Article

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        exclude = ('owner', 'is_deleted', 'last_updated')

controledeartigos/articles/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect, get_object_or_404
from articles.models import Article
from articles.forms import ArticleForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth.models import User
from django.http import Http404



@login_required(login_url='/accounts/login')
def flow_list_articles(request):
    template_name = 'articles/list_articles.html'
    articles = Article.objects.filter(is_deleted=False, product='FW').order_by('last_updated')
    users = User.objects.all()
    if request.GET.get('date_start_with') and request.GET.get('date_end_with'):
            start_with = request.GET.get('date_start_with')
            end_with = request.GET.get('date_end_with')
            articles = articles.filter(last_updated__range=(start_with, end_with))
    if request.GET.get('usuario'):
        user_id = request.GET.get('usuario')
        user = get_object_or_404(User, id=user_id)
        articles = articles.filter(owner=user)    
    if request.GET.get('query'):
        query = request.GET.get('query')
        articles = articles.filter(name__icontains=query)
    if request.GET.get('pendente'):
        articles = articles.filter(Q(status='AF') | Q(status='AR'))
    if request.GET.get('realizado'):
        articles = articles.filter(Q(status='FF') | Q(status='AO'))
   
    context = {
        'articles': articles,
        'product': 'Flow',
        'users': users
    }
    return render(request, template_name, context)

@login_required(login_url='accounts/login')
def start_list_articles(request):
    template_name = 'articles/list_articles.html'
    articles = Article.objects.filter(is_deleted=False, product='ST').order_by('last_updated')
    users = User.objects.all()

    if request.GET.get('date_start_with') and request.GET.get('date_end_with'):
            start_with = request.GET.get('date_start_with')
            end_with = request.GET.get('date_end_with')
            articles = articles.filter(last_updated__range=(start_with, end_with))
    if request.GET.get('usuario'):
        user_id = request.GET.get('usuario')
        user = get_object_or_404(User, id=user_id)
        articles = articles.filter(owner=user)    
    if request.GET.get('query'):
        query = request.GET.get('query')
        articles = articles.filter(name__icontains=query)
    if request.GET.get('pendente'):
        articles = articles.filter(Q(status='AF') | Q(status='AR'))
    if request.GET.get('realizado'):
        articles = articles.filter(Q(status='FF') | Q(status='AO'))
    context = {
        'articles': articles,
        'product': 'Start',
        'users': users
    }
    return render(request, template_name, context)

@login_required(login_url='accounts/login')
def celero_list_articles(request):
    template_name = 'articles/list_articles.html'
    articles = Article.objects.filter(is_deleted=False, product='CE').order_by('last_updated')
    users = User.objects.all()
    if request.GET.get('date_start_with') and request.GET.get('date_end_with'):
            start_with = request.GET.get('date_start_with')
            end_with = request.GET.get('date_end_with')
            articles = articles.filter(last_updated__range=(start_with, end_with))
    if request.GET.get('usuario'):
        user_id = request.GET.get('usuario')
        user = get_object_or_404(User, id=user_id)
        articles = articles.filter(owner=user)    
    if request.GET.get('query'):
        query = request.GET.get('query')
        articles = articles.filter(name__icontains=query)
    if request.GET.get('pendente'):
        articles = articles.filter(Q(status='AF') | Q(status='AR'))
    if request.GET.get('realizado'):
        articles = articles.filter(Q(status='FF') | Q(status='AO'))
    context = {
        'articles': articles,
        'product': 'Celero',
        'users': users
    }
    return render(request, template_name, context)

@login_required(login_url='accounts/login')
def create_article(request):
    template_name = 'articles/create_article.html'
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.owner = request.user
            f.save()
            messages.success(request, 'Artigo adicionado com sucesso')
        messages.error(request, form.errors)
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)

@login_required(login_url='accounts/login')
def edit_article(request, id):
    template_name = 'articles/edit_article.html'
    context = {}
    article = get_object_or_404(Article, article_id=id, is_deleted=False)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            if article.product == 'CE':
                return redirect('artigos:celero_list_articles')
            elif article.product == 'ST':
                return redirect('artigos:start_list_articles')
            elif article.product == 'FW':
                return redirect('artigos:flow_list_articles')
    else:
        form = ArticleForm(instance=article)
    context['form'] = form
    return render(request, template_name, context)
            
@login_required(login_url='accounts/login')
def delete_article(request, id):
    template_name = 'article/delete_article.html'
    article = get_object_or_404(Article, article_id=id, is_deleted=False)
    article.is_deleted = True
    article.save()
    if article.product == 'CE':
        return redirect('artigos:celero_list_articles')
    elif article.product == 'ST':
        return redirect('artigos:start_list_articles')
    elif article.product == 'FW':
        return redirect('artigos:flow_list_articles')

@login_required(login_url='accounts/login')
def list_deleted_articles(request):
    template_name = 'articles/list_deleted_articles.html'
    context = {}
    deleted_articles = Article.objects.filter(is_deleted=True).order_by('last_updated')
    context['articles'] = deleted_articles
    return render(request, template_name, context)

@login_required(login_url='accounts/login')  
def recuperate_article(request, id):
    template_name = 'article/delete_article.html'
    article = get_object_or_404(Article, article_id=id, is_deleted=True)
    article.is_deleted = False
    article.save()
    if article.product == 'CE':
        return redirect('artigos:celero_list_articles')
    elif article.product == 'ST':
        return redirect('artigos:start_list_articles')
    elif article.product == 'FW':
        return redirect('artigos:flow_list_articles')

@login_required(login_url='accounts/login')
def get_user_pendent_articles(request):
    template_name = 'articles/user_articles.html'
    context = {}
    user = request.user
    articles = Article.objects.filter(Q(status='AR') | Q(status='AF'), owner=user).order_by('name')
    context['articles'] = articles
    return render(request, template_name, context)

@login_required(login_url='accounts/login/')
def change_article_to_done(request, article_id):
    template_name = 'articles/confirm_change_to_done.html'
    context = {}
    article = Article.objects.get(article_id=article_id)
    if article.status == 'AF':
        article.status = 'FF'
        article.save()
    elif article.status == 'AR':
        article.status = 'AO'
        article.save()
    if article.product == 'CE':
        return redirect('artigos:celero_list_articles')
    elif article.product == 'ST':
        return redirect('artigos:start_list_articles')
    elif article.product == 'FW':
        return redirect('artigos:flow_list_articles')

controledeartigos/templates/articles/create_article.html
{% extends 'base.html' %}
{% load widget_tweaks %}



{% block body %}
    
    <div class="container">
        <h1> Adicionar Artigo<h1>
            {% include 'partials/messages.html' %}
        <div class="row">
            <div class="col-md-12">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for={{form.name.id_for_label}}>Nome</label>
                        {{form.name|add_class:"form-control"|attr:"autofocus"}}
                    </div>
                    <div class="form-group">
                        <label for={{form.url.id_for_label}}>Link do Artigo</label>
                        {{form.url|add_class:"form-control"}}
                    </div>
                    <div class="form-group">
                        <label for={{form.status.id_for_label}}>Status</label>
                        {{form.status|add_class:"form-control"}}
                    </div>
                    <div class="form-group">
                        <label for={{form.category.id_for_label}}>Categoria</label>
                        {{form.category|add_class:"form-control"}}
                    </div>
                    <div class="form-group">
                        <label for={{form.status.id_for_label}}>Product</label>
                        {{form.product|add_class:"form-control"}}
                    </div>


                      
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

controledeartigos/templates/articles/edit_article.html
{% extends 'base.html' %}
{% load widget_tweaks %}



{% block body %}
    
    <div class="container">
        <h1> Adicionar Artigo<h1>
            {% include 'partials/messages.html' %}
        <div class="row">
            <div class="col-md-12">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for={{form.name.id_for_label}}>Nome</label>
                        {{form.name|add_class:"form-control"|attr:"autofocus"}}
                    </div>
                    <div class="form-group">
                        <label for={{form.url.id_for_label}}>Link do Artigo</label>
                        {{form.url|add_class:"form-control"}}
                    </div>
                    <div class="form-group">
                        <label for={{form.status.id_for_label}}>Status</label>
                        {{form.status|add_class:"form-control"}}
                    </div>
                    <div class="form-group">
                        <label for={{form.category.id_for_label}}>Categoria</label>
                        {{form.category|add_class:"form-control"}}
                    </div>
                    <div class="form-group">
                        <label for={{form.status.id_for_label}}>Product</label>
                        {{form.product|add_class:"form-control"}}
                    </div>


                      
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

controledeartigos/templates/articles/list_articles.html
{% extends 'base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-12">
              
              {% if product == 'Flow' %}
              <br>
              <h2>Lista de Artigos Flow</h2>
              <br>
              <div class="form-check">
                <form class="form-inline my-2 my-md-0" action="{% url 'articles:flow_list_articles' %}">
                  <div class="row">
                    <div class="col-2">
                      <label>Data de início</label>
                      <input class="form-control" type="date" name="date_start_with">
                    </div>
                    <div class="col-2">
                      <label>Data Final</label>
                      <input class="form-control" type="date"  name="date_end_with">
                    </div>
                    <div class="col-4">
                      <label>Nome do Artigo</label>
                      <input class="form-control" name="query" type="text" placeholder="Pesquisar" aria-label="Search">
                    </div>
                    <div class="form-group col-md-3">
                      <label for="inputState">Feito por</label>
                      <select id="inputState" class="form-control" name="usuario">
                        <option selected value="">Escolha o usuário</option>
                        {% for user in users %}
                        <option value="{{user.id}}">{{user.first_name |default:user.username}}</option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="form-group col-md-1">
              
                      <button class="btn btn-outline-success my-2 my-sn-0" type="submit">Filtrar</button>
                    </div>
                  </div>
                  <br>
                  <div class="row">
                    <div class="col-1">
                      <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" name="pendente">
                        <label class="form-check-label" for="inlineCheckbox1">Pendente</label>
                      </div>
                    </div>
                    <div class="col-1">
                      <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" name="realizado">
                        <label class="form-check-label" for="inlineCheckbox1">Realizado</label>
                      </div>
                    </div>
                   
                  </div>
                  
              </form>
              {% elif product == 'Start' %}
              <br>
              <h2>Lista de Artigos Start</h2>
              <br>
              <div class="form-check">
                <form class="form-inline my-2 my-md-0" action="{% url 'articles:start_list_articles' %}">
                  <div class="row">
                    <div class="col-2">
                      <label>Data de início</label>
                      <input class="form-control" type="date" name="date_start_with">
                    </div>
                    <div class="col-2">
                      <label>Data Final</label>
                      <input class="form-control" type="date"  name="date_end_with">
                    </div>
                    <div class="col-4">
                      <label>Nome do Artigo</label>
                      <input class="form-control" name="query" type="text" placeholder="Pesquisar" aria-label="Search">
                    </div>
                    <div class="form-group col-md-3">
                      <label for="inputState">Feito por</label>
                      <select id="inputState" class="form-control" name="usuario">
                        <option selected value="">Escolha o usuário</option>
                        {% for user in users %}
                        <option value="{{user.id}}">{{user.first_name |default:user.username}}</option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="form-group col-md-1">
              
                      <button class="btn btn-outline-success my-2 my-sn-0" type="submit">Filtrar</button>
                    </div>
                  </div>
                  <br>
                  <div class="row">
                    <div class="col-1">
                      <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" name="pendente">
                        <label class="form-check-label" for="inlineCheckbox1">Pendente</label>
                      </div>
                    </div>
                    <div class="col-1">
                      <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" name="realizado">
                        <label class="form-check-label" for="inlineCheckbox1">Realizado</label>
                      </div>
                    </div>
                   
                  </div>
                  
              </form>
              {% elif product == 'Celero' %}
              <br>
              <h2>Lista de Artigos Celero</h2>
              <br>
              <div class="form-check">
                <form class="form-inline my-2 my-md-0" action="{% url 'articles:celero_list_articles' %}">
                  <div class="row">
                    <div class="col-2">
                      <label>Data de início</label>
                      <input class="form-control" type="date" name="date_start_with">
                    </div>
                    <div class="col-2">
                      <label>Data Final</label>
                      <input class="form-control" type="date"  name="date_end_with">
                    </div>
                    <div class="col-4">
                      <label>Nome do Artigo</label>
                      <input class="form-control" name="query" type="text" placeholder="Pesquisar" aria-label="Search">
                    </div>
                    <div class="form-group col-md-3">
                      <label for="inputState">Feito por</label>
                      <select id="inputState" class="form-control" name="usuario">
                        <option selected value="">Escolha o usuário</option>
                        {% for user in users %}
                        <option value="{{user.id}}">{{user.first_name |default:user.username}}</option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="form-group col-md-1">
              
                      <button class="btn btn-outline-success my-2 my-sn-0" type="submit">Filtrar</button>
                    </div>
                  </div>
                  <br>
                  <div class="row">
                    <div class="col-1">
                      <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" name="pendente">
                        <label class="form-check-label" for="inlineCheckbox1">Pendente</label>
                      </div>
                    </div>
                    <div class="col-1">
                      <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" name="realizado">
                        <label class="form-check-label" for="inlineCheckbox1">Realizado</label>
                      </div>
                    </div>
                   
                  </div>
                  
              </form>
              {% endif %}
                
              
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Nome do Artigo</th>
                        <th scope="col">Status</th>
                        <th scope="col">Feito por</th>
                        <th scope="col">Última edição</th>
                        <th scope="col">Ações</th>
                      </tr>
                    </thead>
                    <tbody>
                          {% for article in articles  %}
                          <tr>
                            <td>{{article.name}}</td>
                            <td>{{article.get_status_display}}</td>
                            <td>{{article.owner.first_name}}</td>
                            <td>{{article.last_updated}}</td>

                            <td>
                              <a href="#" class="btn btn-primary btn-sm">Detalhes</a>
                              <a href="{% url 'artigos:edit_article' article.article_id  %}" class="btn btn-primary btn-sm">Editar</a>
                              <a href="{% url 'artigos:delete_article' article.article_id  %}" class="btn btn-danger btn-sm confirm-delete" data-toggle="modal", data-target="#confirmDeleteModal" id="deleteButton-{{ article.article_id }}" >Excluir</a>
                            </td>
                          </tr>
                          {% endfor %}   
                    </tbody>
                  </table>
            </div>
        </div>
        {% include 'partials/confirm_delete_modal.html' %}
    </div>



{% endblock body %}

controledeartigos/templates/articles/list_deleted_articles.html
{% extends 'base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Nome</th>
                        <th scope="col">Status</th>
                        <th scope="col">Feito por</th>
                        <th scope="col">Data de Deleção</th>
                        <th scope="col">Ações</th>
                      </tr>
                    </thead>
                    <tbody>
                          {% for article in articles  %}
                          <tr>
                            <td>{{article.name}}</td>
                            <td>{{article.get_status_display}}</td>
                            <td>{{article.owner.first_name}}</td>
                            <td>{{article.last_updated}}</td>

                            <td>
                              <a href="{% url 'artigos:recuperate_article' article.article_id  %}" class="btn btn-danger btn-sm confirm-recuperation" data-toggle="modal", data-target="#confirmRecuperationModal" id="recuperationButton-{{ article.article_id }}" >Recuperar</a>
                            </td>
                          </tr>
                          {% endfor %}   
                    </tbody>
                  </table>
            </div>
        </div>
        {% include 'partials/confirm_article_recuperation.html' %}
    </div>



{% endblock body %}

controledeartigos/templates/articles/user_articles.html
{% extends 'base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <br>
                <h2>Minhas tarefas pendentes</h2>
                <form class="form-inline my-2 my-md-0" action="{% url 'articles:home' %}"></form>
                    <div class="row">
                      <div class="col-4">
                      <label>Nome do Artigo</label>
                      <input class="form-control" name="query" type="text" placeholder="Pesquisar" aria-label="Search">
                    </div>
                    <div class="col-4"></div>
                    <button class="btn btn-outline-success my-2 my-sn-0" type="submit">Filtrar</button>
                  </div>
                  </div>
                </form>
                <br>
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Nome</th>
                        <th scope="col">Status</th>
                        <th scope="col">Produto</th>
                        <th scope="col">Última edição</th>
                        <th scope="col">Ações</th>
                      </tr>
                    </thead>
                    <tbody>
                          {% for article in articles  %}
                          <tr>
                            <td>{{article.name}}</td>
                            <td>{{article.get_status_display}}</td>
                            <td>{{article.get_product_display}}</td>
                            <td>{{article.last_updated}}</td>

                            <td>
                              
                              {% if article.status == 'AF' %}
                              <a href="{% url 'artigos:change_to_done' article.article_id  %}" class="btn btn-success btn-sm confirm-change" data-toggle="modal", data-target="#confirmChangeModal" id="changeButton-{{ article.article_id }}">Feito</a>
                              {% elif article.status == 'AR' %}
                              <a href="{% url 'artigos:change_to_done' article.article_id  %}" class="btn btn-info btn-sm confirm-change" data-toggle="modal", data-target="#confirmChangeModal" id="changeButton-{{ article.article_id }}">Atualizar</a>
                              {% endif %}
                              
                            </td>
                          </tr>
                          {% endfor %}   
                    </tbody>
                  </table>
            </div>
        </div>
        {% include 'partials/confirm_change_to_done.html' %}
    </div>



{% endblock body %}