controledeartigos/articles/urls.py
from django.urls import path
from articles import views


app_name='articles'

urlpatterns = [
    path('flow/', views.flow_list_articles, name='flow_list_articles'),
    path('start/', views.start_list_articles, name='start_list_articles'),
    path('celero/', views.celero_list_articles, name='celero_list_articles'),
    path('novo_artigo/', views.create_article, name='create_article'),
    path('editar/<str:id>', views.edit_article, name='edit_article'),
    path('deletar/<str:id>', views.delete_article, name='delete_article'),
    path('deletados/', views.list_deleted_articles, name='list_deleted_articles'),
    path('recuperar/<str:id>', views.recuperate_article, name='recuperate_article'),
    path('realizado/<str:article_id>', views.change_article_to_done, name='change_to_done'),
    path('', views.get_user_pendent_articles, name='home'),
]

controledeartigos/controledeartigos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('artigos/', include('articles.urls', namespace='artigos')),
    path('accounts/', include("allauth.urls")),
    path('', include('articles.urls', namespace='home')),
]

controledeartigos/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <title>{% block title %} Controle de Artigos {% endblock title %}</title>
    </head>

    <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand" href="#">Controle de Artigos</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          {% if user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'artigos:home' %}">Minhas tarefas <span class="sr-only"></span></a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Celero
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'artigos:celero_list_articles' %}">Lista de Artigos</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'artigos:create_article' %}">Novo Artigo</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Flow
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'artigos:flow_list_articles' %}">Lista de Artigos</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'artigos:create_article' %}">Novo Artigo</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Start
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'artigos:start_list_articles' %}">Lista de Artigos</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'artigos:create_article' %}">Novo Artigo</a>
                </div>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'artigos:list_deleted_articles' %}">Artigos Deletados <span class="sr-only"></span></a>
              </li>
            </ul>
          </div>
          {% endif %}
            <ul class="navbar-nav">
              {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{user.first_name}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                  
              </li>
              {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
              </li>
              {% endif %}
          </ul>
        </div>
          
        </nav>

        {% block body %}
              
        {% endblock body %}

        <footer>
          <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
          <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
          <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
          <script src="{% static 'js/jquery.mask.min.js' %}"></script>
          <script src="{% static 'js/mask.js' %}"></script>

          <script>
            $(document).on('click', '.confirm-delete', function() {
                $('#confirmDeleteModal').attr('caller-id', $(this).attr('id'));
            });
            $(document).on('click', '#confirmDeleteButtonModal', function(){
                var caller = $('#confirmDeleteButtonModal').closest('.modal').attr('caller-id');
                window.location = $('#'.concat(caller)).attr('href');
            });
            $(document).on('click', '.confirm-recuperation', function() {
                $('#confirmRecuperationModal').attr('caller-id', $(this).attr('id'));
            });
            $(document).on('click', '#confirmRecuperationButtonModal', function(){
                var caller = $('#confirmRecuperationButtonModal').closest('.modal').attr('caller-id');
                window.location = $('#'.concat(caller)).attr('href');
            });
            $(document).on('click', '.confirm-change', function() {
                $('#confirmChangeModal').attr('caller-id', $(this).attr('id'));
            });
            $(document).on('click', '#confirmChangeButtonModal', function(){
                var caller = $('#confirmChangeButtonModal').closest('.modal').attr('caller-id');
                window.location = $('#'.concat(caller)).attr('href');
            });
          </script>
        </footer>
    </body>
</html>